#!/bin/bash
# Shortcuts for common developer tasks

# Setup the virtual environment via Poetry and install pre-commit hooks
run_install() {

   # Create and update the virtualenv
   poetry install -v
   if [ $? != 0 ]; then
      exit 1
   fi

   # Upgrade embedded packages within the virtualenv
   # This command sometimes returns $?=1 on Windows, even though it succeeds <sigh>
   poetry run pip install --quiet --upgrade pip wheel setuptools 2>/dev/null

   # Install the pre-commit hooks
   poetry run pre-commit install 
   if [ $? != 0 ]; then
      exit 1
   fi

}

# Activate the current Poetry virtual environment
run_activate() {
   echo "source "$(dirname $(poetry run which python) 2>/dev/null)/activate""
}

# Run the Pylint code checker
run_pylint() {
   echo "Running pylint checks..."

   poetry run which pylint > /dev/null
   if [ $? != 0 ]; then
      run_install
   fi

   poetry run pylint -j 0 src/sensortrack tests
   if [ $? != 0 ]; then
      exit 1
   fi

   echo "done"
}

# Run the MyPy code checker
run_mypy() {
   echo "Running mypy checks..."

   poetry run which mypy > /dev/null
   if [ $? != 0 ]; then
      run_install
   fi

   poetry run mypy
   if [ $? != 0 ]; then
      exit 1
   fi

   echo "done"
}

# Run the black code formatter
run_black() {
   echo "Running black formatter..."

   poetry run which black > /dev/null
   if [ $? != 0 ]; then
      run_install
   fi

   poetry run black $* .
   if [ $? != 0 ]; then
      exit 1
   fi

   echo "done"
}

# Run the isort import formatter
run_isort() {
   echo "Running isort formatter..."

   poetry run which isort > /dev/null
   if [ $? != 0 ]; then
      run_install
   fi

   poetry run isort $* .
   if [ $? != 0 ]; then
      exit 1
   fi

   echo "done"
}

# Run the unit tests, optionally with coverage
run_pytest() {
   coverage="no"
   html="no"

   while getopts ":ch" option; do
     case $option in
       c) 
         coverage="yes"
         ;;
       h) 
         html="yes"
         ;;
       ?) 
         echo "invalid option -$OPTARG"
         exit 1
         ;;
     esac
   done

   poetry run which pytest > /dev/null
   if [ $? != 0 ]; then
      run_install
   fi

   if [ $coverage == "yes" ]; then
      poetry run coverage run -m pytest --testdox tests
      if [ $? != 0 ]; then
         exit 1
      fi

      poetry run coverage report
      if [ $html == "yes" ]; then
         poetry run coverage html -d .htmlcov
         $(which start || which open) .htmlcov/index.html 2>/dev/null  # start on Windows, open on MacOS and Debian (post-bullseye)
      fi
   else
      poetry run pytest --testdox tests
      if [ $? != 0 ]; then
         exit 1
      fi
   fi
}

# Run the broader Tox test suite used by the GitHub CI action
run_tox() {
   poetry run which tox > /dev/null
   if [ $? != 0 ]; then
      run_install
   fi

   poetry run tox -c .toxrc -e "checks,coverage"
   if [ $? != 0 ]; then
      exit 1
   fi
}

# Run the REST server at localhost:8080
run_server() {
   poetry run which uvicorn > /dev/null
   if [ $? != 0 ]; then
      run_install
   fi

   # using host 0.0.0.0 makes the server available on the local network
   poetry run uvicorn sensortrack.server:API \
      --port 8080 \
      --host 0.0.0.0 \
      --app-dir src --reload \
      --log-config config/local/sensortrack/server/logging.yaml \
      --env-file config/local/sensortrack/server/server.env
}

# Run the InfluxDB & Grafana servers via docker-compose
run_database() {
   docker-compose up
}

# Build release artifacts 
run_build() {
   echo "Building release artifacts..."

   rm -f dist/*
   poetry version
   poetry build

   echo "done"
}

# Release a specific version and tag the code
run_release() {
   if [ $# != 1 ]; then
      echo "run release <version>"
      exit 1
   fi

   VERSION=$(echo "$1" | sed 's/^v//') # so you can use "0.1.5 or "v0.1.5"
   COPYRIGHT="$(date +'%Y')"
   DATE=$(date +'%d %b %Y')
   TAG="v$VERSION" # follow PEP 440 naming convention
   FILES="NOTICE pyproject.toml Changelog"
   MESSAGE="Release v$VERSION"

   if [ "$(git branch -a | grep '^\*' | sed 's/^\* //')" != "master" ]; then
      echo "*** You are not on master; you cannot release from this branch"
      exit 1
   fi

   git tag -l "$TAG" | grep -q "$TAG"
   if [ $? = 0 ]; then
      echo "*** Version v$VERSION already tagged"
      exit 1
   fi

   head -1 Changelog | grep -q "^Version $VERSION\s\s*unreleased"
   if [ $? != 0 ]; then
      echo "*** Unreleased version v$VERSION is not at the head of the Changelog"
      exit 1
   fi

   poetry version $VERSION
   if [ $? != 0 ]; then
      echo "*** Failed to update version"
      exit 1
   fi

   sed -i "s/^Version $VERSION\s\s*unreleased/Version $VERSION     $DATE/g" Changelog
   sed -i -E "s/(^ *Copyright \(c\) *)([0-9,-]+)( *Kenneth.*$)/\1$COPYRIGHT\3/" NOTICE

   git diff $FILES

   git commit --no-verify -m "$MESSAGE" $FILES
   if [ $? != 0 ]; then
      echo "*** Commit step failed"
      exit 1
   fi

   git tag -a "$TAG" -m "$MESSAGE"
   if [ $? != 0 ]; then
      echo "*** Tag step failed"
      exit 1
   fi

   rm -f dist/*

   poetry build
   if [ $? != 0 ]; then
      echo "*** Build step failed."
      exit 1
   fi

   tar zcf dist/sensortrack-config-$VERSION.tar.gz \
       -C config/installed --mode="go-rwx" --owner=github --group=github .
   if [ $? != 0 ]; then
      echo "*** Config bundle step failed."
      exit 1
   fi

   echo ""
   echo "*** Version v$VERSION has been released and committed"
   echo ""
   echo "Next, push: git push --follow-tags"
   echo ""
   echo "Then go to: https://github.com/pronovic/smartapp-sensortrack/releases/tag/v$VERSION"
   echo ""
   echo "Convert the tag to a release and attach build artifacts:"
   ls -l dist
   echo ""
}

# Execute one of the developer tasks
case $1 in
   install|setup)
      run_install
      ;;
   activate)
      run_activate
      ;;
   requirements)
      run_requirements
      ;;
   black)
      run_black
      ;;
   isort)
      run_isort
      ;;
   *lint)
      run_pylint
      ;;
   mypy)
      run_mypy
      ;;
   format)
      run_black
      echo ""
      run_isort
      ;;
   check*)
      run_black --check
      echo ""
      run_isort --check-only
      echo ""
      run_mypy
      echo ""
      run_pylint
      ;;
   pytest|test*)
      shift 1
      run_pytest $*
      ;;
   tox)
      run_tox
      ;;
   server)
      shift 1
      run_server $*
      ;;
   database|influx*|grafana)
      run_database
      ;;
   build)
      run_build
      ;;
   release)
      shift 1
      run_release $*
      ;;
   *)
      echo ""
      echo "------------------------------------"
      echo "Shortcuts for common developer tasks"
      echo "------------------------------------"
      echo ""
      echo "Usage: run <command>"  
      echo ""
      echo "- run install: Setup the virtualenv via Poetry and install pre-commit hooks"
      echo "- run activate: Print command needed to activate the Poetry virtualenv"
      echo "- run format: Run the code formatters"
      echo "- run checks: Run the code checkers"
      echo "- run test: Run the unit tests"
      echo "- run test -c: Run the unit tests with coverage"
      echo "- run test -ch: Run the unit tests with coverage and open the HTML report"
      echo "- run tox: Run the Tox test suite used by the GitHub CI action"
      echo "- run server: Run the REST server at localhost:8080"
      echo "- run database: Run the InfluxDB & Grafana servers via docker-compose"
      echo "- run release: Release a specific version and tag the code"
      echo "- run build: Build artifacts in the dist/ directory"
      echo ""
      exit 1
esac
